server:
  port: 8761
spring:
  application:
    name: Eureka Server


eureka:
  server:
    enableSelfPreservation: true
    eviction-interval-timer-in-ms: 5000
  instance:
    leaseRenewalIntervalInSeconds: 3
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
